### ISSUE TITLE
Question: Direct way to access second partition?

### ISSUE THREAD

**Issue by Clydefrosch** [toolboc/psx-pi-smbshare#1]
Not sure if this is an issue on my end, or intended behavior, but I haven't been able to access the leftover partition from an sd card reader to transfer files. i see its there in disk management, and i can connect to it through network, but i cant access or mount it in any way directly. since over wifi, I'm not getting more than 1mb/s in transfer speeds, would it work to just connect the pi to my pc directly through ethernet?

Asking since I'd need to order an adapter first to try myself

**Comment by toolboc** [comment]
@Clydefrosch , by default Raspbian creates partitions at /boot and /rootfs.  The /boot parition is formatted to FAT and can be read on most OS's (Windows, Mac, Linux) without issue.  This is the partition that allows you to setup wifi and other boot configurations.  The remaining space on /rootfs is formatted to ext4 and is read/writable out of box on most Linux distros but [requires configuration of an ext filesystem driver](https://www.howtogeek.com/112888/3-ways-to-access-your-linux-partitions-from-windows/) to work on Mac or Windows.  

That said, you can totally connect the pi to a pc directly via ethernet cable to transfer data to the SMB share.  When you plug the device in, the pc should get an ip in the 192.168.2.x range.  As long as that happens you should be able to access the drive without issue.
