### ISSUE TITLE
"Upgrading WEB UI" loop

### ISSUE THREAD

**Issue by domeus** [toolboc/psx-pi-smbshare#15]
WEB GUI just looping "UPGRADING WEB UI" and newer ends. Any tips?

**Comment by aapokaapo** [comment]
Delete the webui.zip in /home/user/.xlink/

**Comment by domeus** [comment]
> Delete the webui.zip in /home/user/.xlink/

Thanks, now webui returns "404 Page Not Found" I removed file from  /root/.xlink/webui.zip because Im using raspberry pi image version

**Comment by aapokaapo** [comment]
After deleting that zip, you need to restart xlink. It should autoupdate and download the latest webui.zip

**Comment by domeus** [comment]
> After deleting that zip, you need to restart xlink. It should autoupdate and download the latest webui.zip

Rebooted, still looping :(

**Comment by aapokaapo** [comment]
Interesting, do you mind joining the xlink discord so we coukd troubleshoot this further https://discord.gg/aResBT

**Comment by domeus** [comment]
> Interesting, do you mind joining the xlink discord so we could troubleshoot this further https://discord.gg/aResBT

Just joined, looks like someone else have same issue

**Comment by toolboc** [comment]
It looks like there have been some changes that require updating the XlinkKai client, this has been addressed in https://github.com/toolboc/psx-pi-smbshare/commit/1a584a182bd7e767d81d6309d17e061dbe4d8850
