### ISSUE TITLE
GSM Settings - "Error writing settings!"

### ISSUE THREAD

**Issue by xhnnsx** [toolboc/psx-pi-smbshare#17]
Hey, i just installed your awesome tool on my RPI4. I've attached a NTSF-USB-HDD. It works with my PS2 so i can see my games :). Is there any chance to write the "per game gsm settings" to the hdd?
Cheers

**Comment by toolboc** [comment]
This might be a limitation with NTSF drives as they may be mounting as read-only.  I don't have a drive to test myself, but you may be able to verify by [starting an SSH session with the psx-pi-smbshare](https://www.raspberrypi.org/documentation/remote-access/ssh/).  You can find the mount point of your NTFS drive at /media/.  Try running `ls -la` in that directory to see if the filesystem is being mounted read-only.
