### ISSUE TITLE
Disabling DHCP server

### ISSUE THREAD

**Issue by lostless** [toolboc/psx-pi-smbshare#19]
Is there instructions on how to disable the DHCP server and have the pi get an address from my router? I would be nice to access the pi from my local network and not have it dedicated to just my PS2.  Or perhaps have an 2nd image with the DHCP server disabled for local network use as well without causing issues making a random second subnet that just knocks out many devices on a LAN.

**Comment by toolboc** [comment]
The pi can get an ip address from a router by enabling wifi, either by using the onboard WiFi present on some models of Pi 2/3 or a compatible WiFi USB adapter.  There is no need to disable the DHCP server, the Wifi will register as separate interface on wlan0 in addition to the ethernet connection on eth0.

https://github.com/toolboc/psx-pi-smbshare#configuring-wireless-network
