### ISSUE TITLE
External HD Power Issue

### ISSUE THREAD

**Issue by ProtoCas** [toolboc/psx-pi-smbshare#25]
Setup is great however please add in the readme that if attempting this with an external hard drive to use a powered USB Hub to accommodate the adequate power needed to function properly with the Raspberry Pi. Thank you :)

**Comment by toolboc** [comment]
Updated, see: https://github.com/toolboc/psx-pi-smbshare/blob/master/README.md#accessing-usb-drives-on-the-smb-share
