### ISSUE TITLE
(no an issue) is posible to add an automatic port forward for mobile carrier to use with xlink kai?

### ISSUE THREAD

**Issue by alfredox123** [toolboc/psx-pi-smbshare#26]
i dont know if this is even posible but the thing is, most of the time my isp is just plain bad and cant play online, however my mobile carrier (movistar) its better for online than my isp. the thing is that when i use mobile carrier to play online with xlink kai im not reachable which is normal since you cant open ports with mobile carriers. BUT someone said that i can bypass this using a vpn? if this can be added to your OS this can be a "portable"/self contained solution for xlink kai with almost everything automated for that part atleast, or maybe im overthinking, thanks for your time and awesome work. i use this for my xbox, ps2 and ps vita so far without problems.

Maybe this is something i should be asking on xlink kai now that i think of it

**Comment by toolboc** [comment]
You could investigate [running a VPN client on the Raspberry Pi](https://www.tomshardware.com/reviews/raspberry-pi-vpn-gateway,6103.html).  Agree that this question might be better suited for the XlinkKai forums or your ISP.  Will close for now, but please update if you find a workaround for your setup.
