### ISSUE TITLE
Error trying to save game configs (like Modes)

### ISSUE THREAD

**Issue by Clydefrosch22** [toolboc/psx-pi-smbshare#3]
Ok, final issue, I swear.
Trying to save game configurations (triangle menu in OPL) produces an error "Error writing settings!", potentially because there's only reading permissions set?

**Comment by toolboc** [comment]
@Clydefrosch22 , can you double-check that this issue is also resolved by the fix supplied for #2 ?

**Comment by toolboc** [comment]
@Clydefrosch22 ,

Awesome!  Thanks for being an awesome user and for assisting in testing and development!  Always happy to help!

**Comment by Clydefrosch22** [comment]
I'm not sure if I'll be able to contribute much else, the only other thing I had a few minutes of mild issues with was setting up wifi cause I kept typing ssid and password in "<>"  without removing <>.

Everything else, at least as far as using this for a ps2, was as self-explanatory as it would get for someone new to both ps2 hacking and using a raspberry pi.
