### ISSUE TITLE
psx-pi-smbshare on lakka

### ISSUE THREAD

**Issue by kieuphong** [toolboc/psx-pi-smbshare#31]
Hi, 

Can you make this work on top of lakka on rpi3?  I don't want to waste a pi 3 just to use smbshare.  Thanks!

KP

**Comment by toolboc** [comment]
@kieuphong,

This will probably work by running the commands mentioned [here](https://github.com/toolboc/psx-pi-smbshare#upgrading-an-existing-install) on top of your existing installation:

> cd ~
> wget -O setup.sh https://raw.githubusercontent.com/toolboc/psx-pi-smbshare/master/setup.sh
> chmod 755 setup.sh
> sudo ./setup.sh

**Comment by kieuphong** [comment]
I did that and got this:

Lakka (official): 2.3.2 (RPi2.arm)
Lakka:~ # cd ~
Lakka:~ # ls
assets       database     overlays     roms         screenshots  system
backup       joypads      playlists    savefiles    setup.sh     thumbnails
cores        lost+found   remappings   savestates   shaders
Lakka:~ # file setup.sh
-sh: file: not found
Lakka:~ # cd ~
Lakka:~ # wget -O setup.sh https://raw.githubusercontent.com/toolboc/psx-pi-smbs
hare/master/setup.sh
Connecting to raw.githubusercontent.com (185.199.109.133:443)
setup.sh             100% |*******************************|  3004   0:00:00 ETA
Lakka:~ # chmod 755 setup.sh
Lakka:~ # nano setup.sh
Lakka:~ # sudo ./setup.sh

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

Lakka:~ # ./setup.sh

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: can't open '/home/pi/samba-init.sh': No such file or directory
chmod: /home/pi/samba-init.sh: No such file or directory

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

./setup.sh: line 31: git: not found
./setup.sh: cd: line 32: can't cd to ps3netsrv--
./setup.sh: line 33: git: not found
./setup.sh: line 34: make: not found

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: can't open '/home/pi/wifi-to-eth-route.sh': No such file or directory
chmod: /home/pi/wifi-to-eth-route.sh: No such file or directory

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

Connecting to raw.githubusercontent.com (185.199.110.133:443)
wget: can't open '/home/pi/setup-wifi-access-point.sh': No such file or director                                                                             y
chmod: /home/pi/setup-wifi-access-point.sh: No such file or directory

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

./setup.sh: line 50: can't create /etc/apt/sources.list.d/teamxlink.list: nonexi                                                                             stent directory

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

./setup.sh: line 55: can't create /home/pi/launchkai.sh: nonexistent directory
chmod: /home/pi/launchkai.sh: No such file or directory
Connecting to raw.githubusercontent.com (185.199.110.133:443)
wget: can't open '/home/pi/automount-usb.sh': No such file or directory
chmod: /home/pi/automount-usb.sh: No such file or directory

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

crontab: unknown user pi

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

./setup.sh: line 75: ps3netsrv++: not found

 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'


 There is no working 'sudo'.

 On debian/ubuntu/all general purpose linux distributions 'sudo'
 allows a permitted user to execute a command as the superuser
 or another user, as specified by the security policy

 With LibreELEC you have root access by default, so you dont need 'sudo'

**Comment by toolboc** [comment]
Looks like your distro does not support "sudo" because it runs as root by default.  

You can either:
A.) Modify the setup.sh script and all supporting scripts to remove all instances of "sudo" and hope that it works
B.) Use another SD card instead of trying to do everything in a single OS image, this would leave you with a supported installation that is free of any potential issues and allow you to only need 1 Raspberry Pi device (just swap the SDs as needed).
