### ISSUE TITLE
Rpi Zero compatibility?

### ISSUE THREAD

**Issue by JIVS** [toolboc/psx-pi-smbshare#9]
Can this run on a zero/zero-W? or it lacks the horsepower to handle it?

**Comment by NutymcNuty** [comment]
I believe the xlink kai binary should work on a normal raspbian install, no idea if this prebuilt distro works.

**Comment by VersatileNinja** [comment]
It works on Pi zero w for all.

**Comment by toolboc** [comment]
Thanks for the confirmation @VersatileNinja!
