### ISSUE TITLE
Image gives me a NO HDMI output on a Rapsberry Pi 3B+

### ISSUE THREAD

**Issue by ghost** [toolboc/psx-pi-smbshare#93]
Got a new Raspberry Pi 3B+ with a 32 GB micro SD card.

- Formatted card to ex Fat using SD card format tool and then Flashed the 1.9 image using balenaEtcher successfully.
- Inserting the card to the Pi and turning it on gives me no HDMI output
- Changed settings in the SD cards config file to see if that does anything - no effect after unchecking the comments.

Confirmed the SD card works as i then installed the raspberry pi lite OS and booted successfully. I cant seem to find any other discussions about this problem outside of issue #74 

There was a possible solution to install raspberry pi lite OS but then run the installer script. Is there any instructions for this as i cant find the script. Any assistance towards the right solution is appreciated.

**Comment by ghost** [comment]
One way around this is to use the desktop version of rapsberry Pi 3B. then run the following script on the command line 

cd ~
wget -O setup.sh https://raw.githubusercontent.com/toolboc/psx-pi-smbshare/master/setup.sh
chmod 755 setup.sh
./setup.sh

**Comment by Kenshokram** [comment]
> One way around this is to use the desktop version of rapsberry Pi 3B. then run the following script on the command line
> 
> cd ~ wget -O setup.sh https://raw.githubusercontent.com/toolboc/psx-pi-smbshare/master/setup.sh chmod 755 setup.sh ./setup.sh

I admit it's my dumbass fault for not remembering this issue, but I came back to using this and legit didn't remember this just doesn't work with Raspberry Pi 3B+, could that be added to the main page as a disclaimer for future people? (or repeat offenders lol)
